### ISSUE TITLE
No module named 'fastai.learner'

### ISSUE THREAD

**Issue by SeekPoint** [bigboNed3/chinese_ulmfit#2]
ub16c9@ub16c9-gpu:~/ub16_prj/chinese_ulmfit$ python3.6 pretraining.py --input_file=tmp/wiki2018-11-14.ids.npy --mapping_file=tmp/wiki2018-11-14.mapping.pkl --dir_path=tmp
Traceback (most recent call last):
  File "pretraining.py", line 3, in <module>
    from helper import *
  File "/home/ub16c9/ub16_prj/chinese_ulmfit/helper.py", line 1, in <module>
    from fastai.learner import *
ModuleNotFoundError: No module named 'fastai.learner'
ub16c9@ub16c9-gpu:~/ub16_prj/chinese_ulmfit$

**Comment by SeekPoint** [comment]
use fastai=0.7.0 can avoid this
